### ISSUE TITLE
ENH: retrieve google search ranking

### ISSUE THREAD

**Issue by westurner** [westurner/chutie#3]
In GitLab by @westurner on Mar 8, 2019, 16:49

Retrieve search ranking for a given URL / domain given certain search phrases.
This may be appropriate for a different tool?

```yaml
- domains:
  - example.com
- searches:
  - example widgets
  - example widgets in city, state
```
